- name: tap homebrew repositories
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{ homebrew_taps }}"

- name: update homebrew
  homebrew: update_homebrew=yes

- name: install homebrew packages
  homebrew:
    name={{ item.name }}
    state={{ item.state|default('latest') }}
    install_options={{ item.install_option|default('') }}
  with_items: "{{ homebrew_packages }}"

- name: install homebrew cask packages
  homebrew_cask:
    name={{ item.name }}
    state={{ item.state|default('present') }}
  with_items: "{{ homebrew_cask_packages }}"

